components:
    security:

    schemas:
        Truck:
            type: object
            properties:
                license_plate:
                    type: string 
                location:
                    type: object
                    properties:
                        current:
                            $ref: "#/components/schemas/Location"
                        history:
                            type: array
                            items: 
                                $ref: "#/components/schemas/Location"
        Location:
            type: object
            properties:
                lat:
                    type: number
                lon:
                    type: number
                insertDate:
                    type: string
                    format: date-time
        Error:
            type: object
            properties:
                message:
                    type: string

        ValidationError:
            type: object
            properties:
                type:
                    type: string
                    enum: [query, body, files, headers]
                message:
                    type: string

    requestBodies:

    responses:
        NotFound:
            description: Not found
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
                    example:
                        message: "Resource not found"
        Forbidden:
            description: Access Forbidden ( Unauthorized )
            content:
                application/json:
                    schema:
                        $ref: "#components/schemas/Error"
                    example:
                        message: "Forbidden"
        InternalServerError:
            description: Internal Server Error
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
                    example:
                        message: "An error ocurred, try again later"
        ServiceUnavailable:
            description: Service Unavailable
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
                    example:
                        message: "Service Unavailable"
        ConnectionRefused:
            description: Connection Refused
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
                    example:
                        message: "127.0.0.1 refused to connect"
        BadRequest:
            description: Bad Request
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/ValidationError"
                    example:
                        message: "Bad request or missing parameters"
        Unauthorized:
            description: Not authenticated
            headers:
                authorization:
                    schema:
                        type: string
                        pattern: 'Basic \w+'
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/ValidationError"
                    example:
                        type: headers
                        message: Unauthorized

        Conflict:
            description: Resource already exists | Conflict
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
                    example:
                        message: "Resource already exists | Conflict"

    examples:

    parameters:

security:
